[theme]
base = "light"
#primaryColor = "red"
#BackgroundColor = "#d8e8f8"
#secondaryBackgroundColor = "#b3b3b3"

primaryColor = '#459AFF'  # '#eeeee4' # light blue
backgroundColor = '#ffffff'  #'#B2D5FF'  # '#F0F3F0' 
secondaryBackgroundColor = '#E6F4FF' # '#678167' 
#font = 'monospace'
